/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sd.ii;

import sun.audio.*;
import java.io.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.sqlite.date.DateFormatUtils;

/**
 *
 * @author Dell
 */
public class StudentLogIn extends javax.swing.JFrame {

    /**
     * Creates new form StudentLogIn
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    private String email;
    final String TeacherUsername = "Sujansir@gmail.com";                        //TeacherloginUsername
    final String TeacherPassword = "123456";                                    //TeacherloginPass

    public StudentLogIn() throws SQLException, ClassNotFoundException {
        super("Student Management System");
        initComponents();
        DatabaseTest db = new DatabaseTest();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        loginimage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logincombobox = new javax.swing.JComboBox<>();
        UsernameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PassField = new javax.swing.JPasswordField();
        Login1 = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 24))); // NOI18N
        jPanel2.setLayout(null);
        jPanel2.add(loginimage);
        loginimage.setBounds(29, 249, 0, 0);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd/ii/Icons/loginpic.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 50, 200, 220);

        jLabel4.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("     Login As:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(290, 100, 134, 34);

        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Email:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(290, 170, 134, 34);

        logincombobox.setBackground(new java.awt.Color(153, 153, 153));
        logincombobox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        logincombobox.setForeground(new java.awt.Color(51, 51, 51));
        logincombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Teacher", "Student" }));
        logincombobox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logincomboboxMouseClicked(evt);
            }
        });
        logincombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logincomboboxActionPerformed(evt);
            }
        });
        jPanel2.add(logincombobox);
        logincombobox.setBounds(440, 100, 250, 34);

        UsernameField.setBackground(new java.awt.Color(204, 204, 204));
        UsernameField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        UsernameField.setForeground(new java.awt.Color(51, 51, 51));
        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });
        jPanel2.add(UsernameField);
        UsernameField.setBounds(440, 170, 250, 34);

        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Password:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(290, 240, 134, 35);

        PassField.setBackground(new java.awt.Color(204, 204, 204));
        PassField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        PassField.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(PassField);
        PassField.setBounds(440, 240, 250, 35);

        Login1.setBackground(new java.awt.Color(51, 51, 51));
        Login1.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        Login1.setForeground(new java.awt.Color(204, 204, 204));
        Login1.setText("Login");
        Login1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Login1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Login1MouseMoved(evt);
            }
        });
        Login1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Login1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Login1MouseReleased(evt);
            }
        });
        Login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login1ActionPerformed(evt);
            }
        });
        jPanel2.add(Login1);
        Login1.setBounds(440, 310, 100, 41);

        Cancel.setBackground(new java.awt.Color(51, 51, 51));
        Cancel.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        Cancel.setForeground(new java.awt.Color(204, 204, 204));
        Cancel.setText("Cancel");
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CancelMouseReleased(evt);
            }
        });
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel2.add(Cancel);
        Cancel.setBounds(590, 310, 100, 41);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd/ii/DesktopBackground/login.jpg"))); // NOI18N
        jLabel3.setText("Sign");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 730, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(741, 423));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void Login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login1ActionPerformed

        InputStream in;

        try {
            // TODO add your handling code here:
            if (DatabaseTest.c == null || DatabaseTest.c.isClosed()) {
                DatabaseTest.c = new DatabaseTest().getConnection();
                conn = DatabaseTest.c;
            } else {
                //DatabaseTest.c = new DatabaseTest().getConnection();
                conn = DatabaseTest.c;
            }
            int option = logincombobox.getSelectedIndex();
            if (option == 1) {
                if (TeacherUsername.equals(UsernameField.getText()) && TeacherPassword.equals(PassField.getText())) {
                    JOptionPane.showMessageDialog(null, "Logged In Successfully");
                    this.dispose();
                    try {
                        in = new FileInputStream(new File("D:\\Netbeans project\\SD-VI\\SD-V\\SD-II\\src\\sd\\ii\\Icons\\login.wav"));       //AudioFile
                        AudioStream audio = new AudioStream(in);
                        AudioPlayer.player.start(audio);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                    //DatabaseTest db = new DatabaseTest();
                    Stuinfo_Admin stuad = new Stuinfo_Admin();
                    stuad.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid username or password");
                }
            } else if (option == 2) {
                pst = conn.prepareStatement("Select * from student where Email=? and Password=?");

                pst.setString(1, UsernameField.getText());
                pst.setString(2, PassField.getText());
                rs = pst.executeQuery();
                
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Logged In Successfully");
                    this.dispose();
                    try {
                        in = new FileInputStream(new File("D:\\Netbeans project\\SD-VI\\SD-V\\SD-II\\src\\sd\\ii\\Icons\\login.wav"));   //audioFile
                        AudioStream audio = new AudioStream(in);
                        AudioPlayer.player.start(audio);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);

                    }
                    email = UsernameField.getText();

                    if (DatabaseTest.c == null || DatabaseTest.c.isClosed()) {
                        DatabaseTest.c = new DatabaseTest().getConnection();
                        conn = DatabaseTest.c;
                    } else {
                        //DatabaseTest.c = new DatabaseTest().getConnection();
                        conn = DatabaseTest.c;
                    }
                    
                    String date = rs.getString("DateofBirth");
                    String date1 = date.substring(0,4);
                    int dt = Integer.parseInt(date1);
                    dt = 2016-dt;
                    
                    Stuinfo_User stuuser = new Stuinfo_User(rs.getString("firstName"), rs.getString("lastName"), "CSE", "2nd", "1st", Integer.toString(dt), rs.getString("Roll"), rs.getInt("ID"));

                    stuuser.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid username or password");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Error: Choose the type of User");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(StudentLogIn.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_Login1ActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldActionPerformed

    private void logincomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logincomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logincomboboxActionPerformed

    private void logincomboboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logincomboboxMouseClicked
        // logincombobox.setBackground(Color.GRAY);
    }//GEN-LAST:event_logincomboboxMouseClicked

    private void Login1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login1MouseDragged
        // Login1.setBackground(Color.red);
    }//GEN-LAST:event_Login1MouseDragged

    private void Login1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login1MouseMoved
        //Login1.setBackground(Color.red);
    }//GEN-LAST:event_Login1MouseMoved

    private void Login1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login1MousePressed
        Login1.setBackground(Color.BLACK);
        Login1.setForeground(Color.white);
    }//GEN-LAST:event_Login1MousePressed

    private void Login1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login1MouseReleased
        Login1.setForeground(new Color(204, 204, 204));
        Login1.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_Login1MouseReleased

    private void CancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMousePressed
        Cancel.setBackground(Color.BLACK);
        Cancel.setForeground(Color.white);
    }//GEN-LAST:event_CancelMousePressed

    private void CancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseReleased
        Cancel.setForeground(new Color(204, 204, 204));
        Cancel.setBackground(new Color(51, 51, 51));
    }//GEN-LAST:event_CancelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try 
                {
                    new StudentLogIn().setVisible(true);
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(StudentLogIn.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Login1;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> logincombobox;
    private javax.swing.JLabel loginimage;
    // End of variables declaration//GEN-END:variables
}
