/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sd.ii;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ayon
 */
public class Stuinfo_Admin extends javax.swing.JFrame implements TableInterface {

    /**
     * Creates new form Stuinfo_Admin
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    String slname, sfname, sroll, sid;

    DefaultTableModel model;

    public Stuinfo_Admin() throws SQLException, ClassNotFoundException {
        super("Student Information");
        initComponents();
        DatabaseTest db = new DatabaseTest();

        Show_Table();
        model = (DefaultTableModel) StudentDatabase.getModel();
        sort();
    }

    //Sort The table
    @Override
    public void sort() {
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>(model);
        StudentDatabase.setRowSorter(sorter);
    }

    //Display Table
    @Override
    public void Show_Table() throws SQLException, ClassNotFoundException {
        if (DatabaseTest.c == null || DatabaseTest.c.isClosed()) {
            DatabaseTest.c = new DatabaseTest().getConnection();
            conn = DatabaseTest.c;
        } else {
            //DatabaseTest.c = new DatabaseTest().getConnection();
            conn = DatabaseTest.c;
        }

        String sql = "select * from student";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();

        StudentDatabase.setModel(DbUtils.resultSetToTableModel(rs));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combosearch = new javax.swing.JComboBox<>();
        txtsearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        butssclear = new javax.swing.JButton();
        butresult = new javax.swing.JButton();
        butlogout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        butadd = new javax.swing.JButton();
        butdelete = new javax.swing.JButton();
        butedit = new javax.swing.JButton();
        butclear = new javax.swing.JButton();
        labroll = new javax.swing.JLabel();
        txtroll = new javax.swing.JTextField();
        labfname = new javax.swing.JLabel();
        txtfname = new javax.swing.JTextField();
        lablname = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        labdateofbirth = new javax.swing.JLabel();
        datechooser = new com.toedter.calendar.JDateChooser();
        labdeterment = new javax.swing.JLabel();
        combodepartment = new javax.swing.JComboBox<>();
        absex = new javax.swing.JLabel();
        jrbmale = new javax.swing.JRadioButton();
        jrbfemale = new javax.swing.JRadioButton();
        labyear = new javax.swing.JLabel();
        comboyear = new javax.swing.JComboBox<>();
        labsemester = new javax.swing.JLabel();
        combosemester = new javax.swing.JComboBox<>();
        labemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StudentDatabase = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 24))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1250, 650));
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText(" Search By:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(930, 44, 80, 30);

        combosearch.setBackground(new java.awt.Color(102, 102, 102));
        combosearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Name", "Roll" }));
        combosearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combosearchActionPerformed(evt);
            }
        });
        jPanel1.add(combosearch);
        combosearch.setBounds(1030, 44, 132, 30);

        txtsearch.setBackground(new java.awt.Color(204, 204, 204));
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtsearch);
        txtsearch.setBounds(1030, 90, 132, 29);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(905, 85, 42, 29);

        butssclear.setBackground(new java.awt.Color(51, 51, 51));
        butssclear.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        butssclear.setForeground(new java.awt.Color(204, 204, 204));
        butssclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd/ii/Icons/Actions-edit-clear-icon.png"))); // NOI18N
        butssclear.setText("Clear");
        butssclear.setMaximumSize(new java.awt.Dimension(77, 27));
        butssclear.setPreferredSize(new java.awt.Dimension(57, 27));
        butssclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butssclearActionPerformed(evt);
            }
        });
        jPanel1.add(butssclear);
        butssclear.setBounds(1050, 140, 97, 30);

        butresult.setBackground(new java.awt.Color(0, 0, 0));
        butresult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd/ii/Icons/stock-photo-result-icon-on-red-glossy-button-grapic-114042883.jpg"))); // NOI18N
        butresult.setToolTipText("Go to Result Section");
        butresult.setBorder(null);
        butresult.setBorderPainted(false);
        butresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butresultActionPerformed(evt);
            }
        });
        jPanel1.add(butresult);
        butresult.setBounds(50, 480, 90, 100);

        butlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd/ii/Icons/Apps-session-logout-icon.png"))); // NOI18N
        butlogout.setToolTipText("Log Out !");
        butlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(butlogout);
        butlogout.setBounds(1186, 66, 48, 48);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd/ii/Icons/Search-icon.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(960, 90, 38, 29);

        butadd.setBackground(new java.awt.Color(51, 51, 51));
        butadd.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        butadd.setForeground(new java.awt.Color(204, 204, 204));
        butadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd/ii/Icons/Button-Add-icon.png"))); // NOI18N
        butadd.setText("Add");
        butadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaddActionPerformed(evt);
            }
        });
        jPanel1.add(butadd);
        butadd.setBounds(50, 190, 100, 30);

        butdelete.setBackground(new java.awt.Color(51, 51, 51));
        butdelete.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        butdelete.setForeground(new java.awt.Color(204, 204, 204));
        butdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd/ii/Icons/Button-Delete-icon.png"))); // NOI18N
        butdelete.setText("Delete");
        butdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butdeleteActionPerformed(evt);
            }
        });
        jPanel1.add(butdelete);
        butdelete.setBounds(50, 250, 100, 30);

        butedit.setBackground(new java.awt.Color(51, 51, 51));
        butedit.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        butedit.setForeground(new java.awt.Color(204, 204, 204));
        butedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd/ii/Icons/edit-file-icon.png"))); // NOI18N
        butedit.setText("Edit");
        butedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buteditActionPerformed(evt);
            }
        });
        jPanel1.add(butedit);
        butedit.setBounds(50, 310, 100, 30);

        butclear.setBackground(new java.awt.Color(51, 51, 51));
        butclear.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        butclear.setForeground(new java.awt.Color(204, 204, 204));
        butclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd/ii/Icons/Clear-icon.png"))); // NOI18N
        butclear.setText("Clear");
        butclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butclearActionPerformed(evt);
            }
        });
        jPanel1.add(butclear);
        butclear.setBounds(50, 370, 100, 30);

        labroll.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        labroll.setForeground(new java.awt.Color(102, 102, 102));
        labroll.setText("Roll:");
        jPanel1.add(labroll);
        labroll.setBounds(230, 190, 100, 28);

        txtroll.setBackground(new java.awt.Color(204, 204, 204));
        txtroll.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        txtroll.setToolTipText("");
        txtroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtrollMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtrollMouseExited(evt);
            }
        });
        txtroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrollActionPerformed(evt);
            }
        });
        jPanel1.add(txtroll);
        txtroll.setBounds(350, 190, 170, 28);

        labfname.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        labfname.setForeground(new java.awt.Color(102, 102, 102));
        labfname.setText("First-Name:");
        jPanel1.add(labfname);
        labfname.setBounds(230, 240, 100, 28);

        txtfname.setBackground(new java.awt.Color(204, 204, 204));
        txtfname.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        txtfname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtfnameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtfnameMouseExited(evt);
            }
        });
        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtfname);
        txtfname.setBounds(350, 240, 170, 28);

        lablname.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lablname.setForeground(new java.awt.Color(102, 102, 102));
        lablname.setText("Last-Name:");
        jPanel1.add(lablname);
        lablname.setBounds(230, 290, 100, 28);

        txtlname.setBackground(new java.awt.Color(204, 204, 204));
        txtlname.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        txtlname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtlnameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtlnameMouseExited(evt);
            }
        });
        txtlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtlname);
        txtlname.setBounds(350, 290, 170, 28);

        labdateofbirth.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        labdateofbirth.setForeground(new java.awt.Color(102, 102, 102));
        labdateofbirth.setText("Date-of-Birth:");
        jPanel1.add(labdateofbirth);
        labdateofbirth.setBounds(230, 340, 95, 28);

        datechooser.setBackground(new java.awt.Color(153, 153, 153));
        datechooser.setForeground(new java.awt.Color(204, 204, 204));
        datechooser.setDateFormatString("yyyy-MM-dd");
        datechooser.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        datechooser.setMaxSelectableDate(new java.util.Date(253370746879000L));
        jPanel1.add(datechooser);
        datechooser.setBounds(350, 340, 170, 28);

        labdeterment.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        labdeterment.setForeground(new java.awt.Color(102, 102, 102));
        labdeterment.setText("Department:");
        jPanel1.add(labdeterment);
        labdeterment.setBounds(230, 430, 88, 28);

        combodepartment.setBackground(new java.awt.Color(51, 51, 51));
        combodepartment.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        combodepartment.setForeground(new java.awt.Color(255, 255, 255));
        combodepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Choose any option>", "CSE", "EEE", "BBA", "CIVIL", "ME", "TEXTILE" }));
        combodepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combodepartmentActionPerformed(evt);
            }
        });
        jPanel1.add(combodepartment);
        combodepartment.setBounds(350, 430, 170, 28);

        absex.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        absex.setForeground(new java.awt.Color(102, 102, 102));
        absex.setText("Sex:");
        jPanel1.add(absex);
        absex.setBounds(230, 390, 28, 18);

        buttonGroup1.add(jrbmale);
        jrbmale.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jrbmale.setForeground(new java.awt.Color(153, 153, 153));
        jrbmale.setText("Male");
        jrbmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbmaleActionPerformed(evt);
            }
        });
        jPanel1.add(jrbmale);
        jrbmale.setBounds(350, 390, 70, 28);

        buttonGroup1.add(jrbfemale);
        jrbfemale.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        jrbfemale.setForeground(new java.awt.Color(153, 153, 153));
        jrbfemale.setText("Female");
        jrbfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbfemaleActionPerformed(evt);
            }
        });
        jPanel1.add(jrbfemale);
        jrbfemale.setBounds(430, 390, 90, 28);

        labyear.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        labyear.setForeground(new java.awt.Color(102, 102, 102));
        labyear.setText("Year:");
        jPanel1.add(labyear);
        labyear.setBounds(230, 480, 45, 28);

        comboyear.setBackground(new java.awt.Color(51, 51, 51));
        comboyear.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        comboyear.setForeground(new java.awt.Color(255, 255, 255));
        comboyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Choose any option>", "1st", "2nd", "3rd", "4th" }));
        comboyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboyearActionPerformed(evt);
            }
        });
        jPanel1.add(comboyear);
        comboyear.setBounds(350, 480, 170, 28);

        labsemester.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        labsemester.setForeground(new java.awt.Color(102, 102, 102));
        labsemester.setText("Semester");
        jPanel1.add(labsemester);
        labsemester.setBounds(230, 530, 63, 28);

        combosemester.setBackground(new java.awt.Color(51, 51, 51));
        combosemester.setFont(new java.awt.Font("Century", 0, 14)); // NOI18N
        combosemester.setForeground(new java.awt.Color(255, 255, 255));
        combosemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Choose any option>", "Spring", "Fall" }));
        combosemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combosemesterActionPerformed(evt);
            }
        });
        jPanel1.add(combosemester);
        combosemester.setBounds(350, 530, 170, 28);

        labemail.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        labemail.setForeground(new java.awt.Color(102, 102, 102));
        labemail.setText("Email:");
        jPanel1.add(labemail);
        labemail.setBounds(230, 580, 90, 28);

        txtemail.setBackground(new java.awt.Color(102, 102, 102));
        txtemail.setFont(new java.awt.Font("Century", 2, 14)); // NOI18N
        txtemail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtemailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtemailMouseExited(evt);
            }
        });
        jPanel1.add(txtemail);
        txtemail.setBounds(350, 580, 170, 28);

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText(" Action Buttons");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 160, 140, 20);

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Insert Data");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(390, 160, 98, 22);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Data Table", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N

        StudentDatabase.setBackground(new java.awt.Color(51, 51, 51));
        StudentDatabase.setBorder(new javax.swing.border.MatteBorder(null));
        StudentDatabase.setFont(new java.awt.Font("Century", 0, 12)); // NOI18N
        StudentDatabase.setForeground(new java.awt.Color(204, 204, 204));
        StudentDatabase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        StudentDatabase.setGridColor(new java.awt.Color(255, 0, 51));
        StudentDatabase.setSelectionBackground(new java.awt.Color(204, 204, 204));
        StudentDatabase.setSelectionForeground(new java.awt.Color(51, 51, 51));
        StudentDatabase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentDatabaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(StudentDatabase);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(570, 190, 650, 420);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sd/ii/DesktopBackground/d1.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(-9, 0, 1260, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1266, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StudentDatabaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentDatabaseMouseClicked
        try {

            if (DatabaseTest.c.isClosed()) {
                DatabaseTest.c = new DatabaseTest().getConnection();
                conn = DatabaseTest.c;
            } else {
                conn = DatabaseTest.c;
            }
            int row = StudentDatabase.getSelectedRow();
            String table_Click = (StudentDatabase.getModel().getValueAt(row, 0).toString());
            String sql = "select * from student where ID ='" + table_Click + "' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();

            if (rs.next()) {
                sid = rs.getString("ID");
                sfname = rs.getString("firstName");
                txtfname.setText(sfname);
                slname = rs.getString("lastName");
                txtlname.setText(slname);
                sroll = rs.getString("Roll");
                txtroll.setText(sroll);
                String semail = rs.getString("Email");
                txtemail.setText(semail);

                String sdateofbirth = rs.getString("DateofBirth");
                DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                Date date = format.parse(sdateofbirth);
                datechooser.setDate(date);

                String sdepartment = rs.getString("Department");

                if (sdepartment.equals("CSE")) {
                    combodepartment.setSelectedIndex(1);
                } else if (sdepartment.equals("EEE")) {
                    combodepartment.setSelectedIndex(2);
                } else if (sdepartment.equals("BBA")) {
                    combodepartment.setSelectedIndex(3);
                } else if (sdepartment.equals("CIVIL")) {
                    combodepartment.setSelectedIndex(4);
                } else if (sdepartment.equals("ME")) {
                    combodepartment.setSelectedIndex(5);
                } else if (sdepartment.equals("TEXTILE")) {
                    combodepartment.setSelectedIndex(6);
                } else {
                    combodepartment.setSelectedIndex(0);
                }

                String syear = rs.getString("Year");

                if (syear.equals("1st")) {
                    comboyear.setSelectedIndex(1);
                } else if (syear.equals("2nd")) {
                    comboyear.setSelectedIndex(2);
                } else if (syear.equals("3rd")) {
                    comboyear.setSelectedIndex(3);
                } else if (syear.equals("4th")) {
                    comboyear.setSelectedIndex(4);
                } else {
                    comboyear.setSelectedIndex(0);
                }

                String ssemester = rs.getString("Semester");

                if (ssemester.equals("Spring")) {
                    combosemester.setSelectedIndex(1);
                } else if (ssemester.equals("Fall")) {
                    combosemester.setSelectedIndex(2);
                } else {
                    combosemester.setSelectedIndex(0);
                }

                String ssex = rs.getString("Sex");

                if (ssex.equals("M")) {
                    jrbmale.setSelected(true);
                } else {
                    jrbfemale.setSelected(true);
                }
            }
        } catch (SQLException | ClassNotFoundException | ParseException e) {
            Logger.getLogger(Stuinfo_Admin.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_StudentDatabaseMouseClicked

    private void txtemailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtemailMouseExited
        txtemail.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_txtemailMouseExited

    private void txtemailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtemailMouseEntered
        txtemail.setBackground(new Color(150, 150, 150));
    }//GEN-LAST:event_txtemailMouseEntered

    private void combosemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combosemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combosemesterActionPerformed

    private void comboyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboyearActionPerformed

    private void jrbfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbfemaleActionPerformed
        S = "F";
    }//GEN-LAST:event_jrbfemaleActionPerformed

    private void jrbmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbmaleActionPerformed
        S = "M";
    }//GEN-LAST:event_jrbmaleActionPerformed

    private void combodepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combodepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combodepartmentActionPerformed

    private void txtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlnameActionPerformed

    private void txtlnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlnameMouseExited
        txtlname.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_txtlnameMouseExited

    private void txtlnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlnameMouseEntered
        txtlname.setBackground(new Color(174, 174, 174));
    }//GEN-LAST:event_txtlnameMouseEntered

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    private void txtfnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfnameMouseExited
        txtfname.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_txtfnameMouseExited

    private void txtfnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtfnameMouseEntered
        txtfname.setBackground(new Color(174, 174, 174));
    }//GEN-LAST:event_txtfnameMouseEntered

    private void txtrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrollActionPerformed

    private void txtrollMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtrollMouseExited
        txtroll.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_txtrollMouseExited

    private void txtrollMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtrollMouseEntered
        txtroll.setBackground(new Color(174, 174, 174));
    }//GEN-LAST:event_txtrollMouseEntered

    private void butclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butclearActionPerformed
        //DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        //Date date = format.parse("2000-01-01");
        txtfname.setText("");
        txtlname.setText("");
        txtroll.setText("");
        buttonGroup1.clearSelection();
        datechooser.setCalendar(null);
        combodepartment.setSelectedIndex(0);
        comboyear.setSelectedIndex(0);
        combosemester.setSelectedIndex(0);
        txtemail.setText("");
    }//GEN-LAST:event_butclearActionPerformed

    private void buteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buteditActionPerformed
        try {
            DatabaseTest db = new DatabaseTest();
            String department = combodepartment.getSelectedItem().toString();
            String year = comboyear.getSelectedItem().toString();
            String semester = combosemester.getSelectedItem().toString();
            db.updateStudent(sid, txtfname.getText(), txtlname.getText(), txtroll.getText(), S, ((JTextField) datechooser.getDateEditor().getUiComponent()).getText(), department, year, semester, txtemail.getText());

            Show_Table();
            model = (DefaultTableModel) StudentDatabase.getModel();
            sort();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Stuinfo_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buteditActionPerformed

    private void butdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butdeleteActionPerformed
        int d = JOptionPane.showConfirmDialog(null, "Do you really want to delete?", "Delete  ", JOptionPane.YES_NO_OPTION);
        if (d == 0) {
            try {
                DatabaseTest db = new DatabaseTest();
                String department = combodepartment.getSelectedItem().toString();
                String year = comboyear.getSelectedItem().toString();
                String semester = combosemester.getSelectedItem().toString();

                String roll = txtroll.getText();

                db.deleteStudent(roll);
                db.deleteResult(roll);

                Show_Table();
                model = (DefaultTableModel) StudentDatabase.getModel();
                sort();
                //AddStudent add = new AddStudent();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(Stuinfo_Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_butdeleteActionPerformed

    private void butaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaddActionPerformed
        try {
            DatabaseTest db = new DatabaseTest();
            String department = combodepartment.getSelectedItem().toString();
            String year = comboyear.getSelectedItem().toString();
            String semester = combosemester.getSelectedItem().toString();
            if (txtfname.getText().equals("") || txtlname.getText().equals("") || txtroll.getText().equals("") || S.equals("") || department.equals("") || year.equals("") || semester.equals("") || txtemail.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "  Enter all the required data");
            } else {
                db.addStudent(txtfname.getText(), txtlname.getText(), txtroll.getText(), S, ((JTextField) datechooser.getDateEditor().getUiComponent()).getText(), department, year, semester, txtemail.getText());
                db.addStudent(txtroll.getText(), null, null, null, null, null, null, null, null, null, null);
            }

            Show_Table();
            model = (DefaultTableModel) StudentDatabase.getModel();
            sort();
            //AddStudent add = new AddStudent();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Stuinfo_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butaddActionPerformed

    private void butlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butlogoutActionPerformed
        this.dispose();
        StudentLogIn stu = null;
        try {
            stu = new StudentLogIn();
        } catch (SQLException ex) {
            Logger.getLogger(Stuinfo_Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Stuinfo_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        stu.setVisible(true);
    }//GEN-LAST:event_butlogoutActionPerformed

    private void butresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butresultActionPerformed
        this.dispose();

        try {
            Stuinfo_Result sr = new Stuinfo_Result(sfname, slname, sroll);
            sr.setVisible(true);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Stuinfo_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butresultActionPerformed

    private void butssclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butssclearActionPerformed
        // TODO add your handling code here:
        txtsearch.setText(null);
        try {
            Show_Table();
            model = (DefaultTableModel) StudentDatabase.getModel();
            sort();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Stuinfo_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butssclearActionPerformed
    //Search with Substring 
    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:

        if (combosearch.getSelectedIndex() == 1) {
            try {
                if (DatabaseTest.c == null || DatabaseTest.c.isClosed()) {
                    DatabaseTest.c = new DatabaseTest().getConnection();
                    conn = DatabaseTest.c;
                } else {
                    //DatabaseTest.c = new DatabaseTest().getConnection();
                    conn = DatabaseTest.c;
                }
                //StudentDatabase.setModel(DbUtils.resultSetToTableModel(null));
                String str = txtsearch.getText();
                String sql = "select * from student where firstName LIKE ? OR lastName LIKE ?";

                pst = conn.prepareStatement(sql);
                pst.setString(1, "%" + str + "%");
                pst.setString(2, "%" + str + "%");
                rs = pst.executeQuery();

                StudentDatabase.setModel(DbUtils.resultSetToTableModel(rs));
                model = (DefaultTableModel) StudentDatabase.getModel();
                sort();

            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(Stuinfo_Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } else if (combosearch.getSelectedIndex() == 2) {
            try {
                if (DatabaseTest.c == null || DatabaseTest.c.isClosed()) {
                    DatabaseTest.c = new DatabaseTest().getConnection();
                    conn = DatabaseTest.c;
                } else {
                    //DatabaseTest.c = new DatabaseTest().getConnection();
                    conn = DatabaseTest.c;
                }
                //StudentDatabase.setModel(DbUtils.resultSetToTableModel(null));
                String str = txtsearch.getText();
                String sql = "select * from student where Roll LIKE ?";

                pst = conn.prepareStatement(sql);
                pst.setString(1, "%" + str + "%");

                rs = pst.executeQuery();

                StudentDatabase.setModel(DbUtils.resultSetToTableModel(rs));
                model = (DefaultTableModel) StudentDatabase.getModel();
                sort();
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(Stuinfo_Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtsearchKeyReleased

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void combosearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combosearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combosearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stuinfo_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stuinfo_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stuinfo_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stuinfo_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Stuinfo_Admin().setVisible(true);
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(Stuinfo_Admin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable StudentDatabase;
    private javax.swing.JLabel absex;
    private javax.swing.JButton butadd;
    private javax.swing.JButton butclear;
    private javax.swing.JButton butdelete;
    private javax.swing.JButton butedit;
    private javax.swing.JButton butlogout;
    private javax.swing.JButton butresult;
    private javax.swing.JButton butssclear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> combodepartment;
    private javax.swing.JComboBox<String> combosearch;
    private javax.swing.JComboBox<String> combosemester;
    private javax.swing.JComboBox<String> comboyear;
    private com.toedter.calendar.JDateChooser datechooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrbfemale;
    private javax.swing.JRadioButton jrbmale;
    private javax.swing.JLabel labdateofbirth;
    private javax.swing.JLabel labdeterment;
    private javax.swing.JLabel labemail;
    private javax.swing.JLabel labfname;
    private javax.swing.JLabel lablname;
    private javax.swing.JLabel labroll;
    private javax.swing.JLabel labsemester;
    private javax.swing.JLabel labyear;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtroll;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
private String S;
}
